### PR TITLE
Aparakian/jkr 17162/facebook business sdk 3.0

### PR DESCRIPTION
**Pull request by aparakian**
One thing here in my last commit, I've removed the code introduced by Ouadia in [this commit](https://github.com/Work4Labs/facebook-python-ads-sdk/commit/0b5d80c4b16d503777d0d65c280c34389c892c3f) because I haven't seen it being used in our code and if ever we need to use it, we now need to use the new endpoints introduced in this version like [create_assigned_users](https://github.com/facebook/facebook-python-business-sdk/blob/218fb913c569d69fb7a9b1bb55f9b104ff5813e2/facebook_business/adobjects/page.py#L534-L562).

Also upstream PR for outdated test: https://github.com/facebook/facebook-python-business-sdk/pull/497

And I took the liberty to add the integration tests to the `tox.ini` file.

### CODE REVIEW

**Comment by m-vdb** [comment]
gros diff 😍

**Comment by fbach** [comment]
ahah @m-vdb

**Comment by aparakian** [comment]
Don't rub it in @m-vdb haha. Do you see the conflicts? I'm crying already 😢

**Comment by m-vdb** [comment]
ahah I feel for you 😣

**Comment by olivierlefloch** [comment]
How am I ever to review this x))

**Comment by aparakian** [comment]
well the only thing to be reviewed were my custom commits at the end basically but I feel confident enough about them so let's move on.

**Comment by olivierlefloch** [comment]
Yes, I reviewed commit by commit ultimately :)

**Pull request merged**
